### ISSUE TITLE
Non-cookies based consent?

### ISSUE THREAD

**Issue by danielkallendorf** [EU-EDPS/website-evidence-collector#105]
Is it possible to set consent, which is not stored as cookies? In my case the consent is stored in the local-storage.
Alternately, Is there a way to prepare the browser manually (click the "I agree" yourself) and use that browser for the scan?

**Comment by rriemann** [comment]
Very briefly:

Without patching the software, you have basically two options:

1. you can use `--no-headless` and `--sleep [time in ms]` to get a browser window and enough time to accept the cookie banner, so that the website can set their localstorage entry.
2. you can create a new chrome profile with chrome, go to the website and accept the cookies to set the localstorage. The option `--browser-profile [path]` allows you to use this custom profile for scans afterwards. I recommend to make a backup of the profile first, so you can repeat the scan if need be without recreating the profile from zero.
