### ISSUE TITLE
Questionable assumption: First Party

### ISSUE THREAD

**Issue by noleakseu** [EU-EDPS/website-evidence-collector#52]
>To be first party, the resource domain must match the domain of the inspected web service or other configured first-party domains. 

Domains lie:
- subdomains can point to another data controller by CNAME cloaking
- can be spoofed in the middle
- can be incorrectly resolved by hosts file locally

Even resolved name does not guarantee that the next request will be processed by the same data controller. For example, due to misconfigured Round-Robin, anycast or multicast addressing.

Please specify technique of existing First Party matching and risks of inadequate conclusion/evidence. I vote for TLS-based matching, where possible.

**Comment by rriemann-eu** [comment]
The HTML output for the layperson includes always a glossary with a definition of terms, including of *first-party*:

![Screenshot_20210303_230415](https://user-images.githubusercontent.com/55188356/109878853-1decad00-7c75-11eb-8daa-5bf2e1c69a34.png)

So the only assumption is that files in the parent path share the party classification of the parent path. Otherwise, it is up to the WEC operator to tell what belongs to the first party.

Documentation can certainly always be improved and I am happy to consider pull requests.

**Comment by noleakseu** [comment]
First-party matching is a common problem. IMO, first-party is any URL (not URI!) that shares TLS certificate of the inspected URL.

For example, spoofed http://domain.com may not represent https://domain.com can, cloaked https://www.domain.com may not represent https://domain.com etc.
